#!/usr/bin/env bash
# Decentralized-BMP V2 — patch BeamMP-Launcher source for deploy-time
# backend re-targeting.
#
# Mirrors patches/apply-server-patch.sh: writes a 256-byte sentinel-led
# host blob into include/_DBMP_BackendUrl.h and rewrites every
# "https://backend.beammp.com" literal to call dbmp::BackendUrl(). The
# shipped binary is host-agnostic; the deploying backend container patches
# the host bytes in place before serving (see backend/scripts/fetch_builds.sh).

set -euo pipefail

if [[ ! -d "src" || ! -d "include" ]]; then
  echo "::error::Run this script from the BeamMP-Launcher source root" >&2
  exit 1
fi

helper_path="include/_DBMP_BackendUrl.h"

python3 - "${helper_path}" <<'PY'
import pathlib, sys

sentinel = b'__DBMP_HOST_SENTINEL_v1\x00'  # exactly 24 bytes
assert len(sentinel) == 24
length = b'\x00\x00\x00\x00'                # uint32 LE = 0 (unpatched marker)
padding = b'\xff' * 228                     # filler forces .rodata storage
blob = sentinel + length + padding
assert len(blob) == 256

init = ', '.join(f'0x{b:02X}' for b in blob)
header = f'''// Auto-generated by Decentralized-BMP V2 (patches/apply-launcher-patch.sh).
// See that script's header comment for the binary layout / patching scheme.
#pragma once

#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <string>

namespace dbmp {{

// 256-byte deploy-time-patchable host blob (see apply-launcher-patch.sh).
inline const unsigned char dbmp_host_blob[256] = {{ {init} }};

inline std::string _resolve_host() {{
    if (const char* env = std::getenv("BMP_BACKEND_HOST")) {{
        if (env[0] != '\\0') return std::string(env);
    }}
    if (const char* env = std::getenv("BMP_BACKEND_URL")) {{
        // Strip scheme + trailing slashes for back-compat with old override.
        std::string v(env);
        while (!v.empty() && v.back() == '/') v.pop_back();
        const std::string sep = "://";
        auto pos = v.find(sep);
        if (pos != std::string::npos) v.erase(0, pos + sep.size());
        if (!v.empty()) return v;
    }}
    std::uint32_t len = 0;
    std::memcpy(&len, dbmp_host_blob + 24, sizeof(len));
    if (len > 0 && len <= 228) {{
        return std::string(reinterpret_cast<const char*>(dbmp_host_blob) + 28, len);
    }}
    return "backend.beammp.com";
}}

inline const std::string& BackendUrl() {{
    static const std::string url = std::string("https://") + _resolve_host();
    return url;
}}

}} // namespace dbmp
'''
pathlib.Path(sys.argv[1]).write_text(header, encoding="utf-8")
PY

echo "[patch] wrote ${helper_path}"

# shellcheck disable=SC2207
files=($(grep -rl --include='*.cpp' --include='*.h' --include='*.hpp' \
    '"https://backend\.beammp\.com"' src include 2>/dev/null || true))

if [[ ${#files[@]} -eq 0 ]]; then
  echo "::error::no occurrences of \"https://backend.beammp.com\" found — upstream changed shape?" >&2
  exit 2
fi

for f in "${files[@]}"; do
  if ! grep -q '_DBMP_BackendUrl\.h' "${f}"; then
    python3 - "${f}" <<'PY'
import pathlib, sys
p = pathlib.Path(sys.argv[1])
lines = p.read_text(encoding="utf-8").splitlines(keepends=True)
inserted = False
for i, line in enumerate(lines):
    if line.lstrip().startswith("#include"):
        lines.insert(i, '#include "_DBMP_BackendUrl.h"\n')
        inserted = True
        break
if not inserted:
    lines.insert(0, '#include "_DBMP_BackendUrl.h"\n')
p.write_text("".join(lines), encoding="utf-8")
PY
  fi

  python3 - "${f}" <<'PY'
import pathlib, sys
p = pathlib.Path(sys.argv[1])
text = p.read_text(encoding="utf-8")
new = text.replace('"https://backend.beammp.com"', 'dbmp::BackendUrl()')
if new != text:
    p.write_text(new, encoding="utf-8")
PY
  echo "[patch] rewrote ${f}"
done

remaining=$(grep -rl --include='*.cpp' --include='*.h' --include='*.hpp' \
    '"https://backend\.beammp\.com"' src include 2>/dev/null || true)
if [[ -n "${remaining}" ]]; then
  echo "::error::leftover hard-coded URLs after patch:" >&2
  echo "${remaining}" >&2
  exit 3
fi

echo "[patch] BeamMP-Launcher source patched OK (${#files[@]} files)"
