#!/usr/bin/env bash
# Decentralized-BMP V2 — patch BeamMP-Launcher source for configurable backend.
#
# Run from the root of a freshly checked-out BeamMP/BeamMP-Launcher source
# tree. Drops in a tiny header that resolves the backend URL once at startup
# (env var BMP_BACKEND_URL → fallback to https://backend.beammp.com), then
# rewrites every occurrence of the hard-coded base URL across .cpp/.h files
# to call that helper instead.
#
# Single-file header, no CMakeLists changes — every TU that previously held
# the literal already compiles, just now resolves the host via getenv().

set -euo pipefail

if [[ ! -d "src" || ! -d "include" ]]; then
  echo "::error::Run this script from the BeamMP-Launcher source root" >&2
  exit 1
fi

helper_path="include/_DBMP_BackendUrl.h"

cat > "${helper_path}" <<'HEADER'
// Auto-generated by Decentralized-BMP V2 (patches/apply-launcher-patch.sh).
// Provides a runtime-resolved replacement for the hard-coded
// "https://backend.beammp.com" base URL used throughout the launcher.
//
// At startup the URL is taken from the BMP_BACKEND_URL environment variable
// if set and non-empty, otherwise it falls back to the upstream default so
// vanilla launches behave identically.
#pragma once

#include <cstdlib>
#include <string>

namespace dbmp {

inline const std::string& BackendUrl() {
    static const std::string url = []() -> std::string {
        if (const char* e = std::getenv("BMP_BACKEND_URL")) {
            if (e[0] != '\0') {
                std::string v(e);
                while (!v.empty() && v.back() == '/') v.pop_back();
                return v;
            }
        }
        return std::string("https://backend.beammp.com");
    }();
    return url;
}

} // namespace dbmp
HEADER

echo "[patch] wrote ${helper_path}"

# Find every source/header file that still holds the upstream literal and
# patch it: prepend an #include of the helper (once) and substitute the
# string literal with `dbmp::BackendUrl()`. The launcher uses the URL only
# in concatenation contexts (`URL + "/path"` or as ctor arg to httplib::
# Client), both of which accept std::string just fine.
mapfile -t files < <(grep -rl --include='*.cpp' --include='*.h' --include='*.hpp' \
    '"https://backend\.beammp\.com"' src include 2>/dev/null || true)

if [[ ${#files[@]} -eq 0 ]]; then
  echo "::error::no occurrences of \"https://backend.beammp.com\" found — upstream changed shape?" >&2
  exit 2
fi

for f in "${files[@]}"; do
  # Insert the include after the file's existing #pragma once / first
  # #include block. Picking the first line that starts with `#include` and
  # adding ours immediately above it keeps the source readable.
  if ! grep -q '_DBMP_BackendUrl\.h' "${f}"; then
    python3 - "${f}" <<'PY'
import pathlib, sys
p = pathlib.Path(sys.argv[1])
lines = p.read_text(encoding="utf-8").splitlines(keepends=True)
inserted = False
for i, line in enumerate(lines):
    s = line.lstrip()
    if s.startswith("#include"):
        lines.insert(i, '#include "_DBMP_BackendUrl.h"\n')
        inserted = True
        break
if not inserted:
    # No include lines (very rare) — insert after the first non-comment line.
    lines.insert(0, '#include "_DBMP_BackendUrl.h"\n')
p.write_text("".join(lines), encoding="utf-8")
PY
  fi

  # Substitute every literal occurrence with the helper call.
  python3 - "${f}" <<'PY'
import pathlib, sys
p = pathlib.Path(sys.argv[1])
text = p.read_text(encoding="utf-8")
new = text.replace('"https://backend.beammp.com"', 'dbmp::BackendUrl()')
if new != text:
    p.write_text(new, encoding="utf-8")
PY

  echo "[patch] rewrote ${f}"
done

# Sanity-check: nothing left.
remaining=$(grep -rl --include='*.cpp' --include='*.h' --include='*.hpp' \
    '"https://backend\.beammp\.com"' src include 2>/dev/null || true)
if [[ -n "${remaining}" ]]; then
  echo "::error::leftover hard-coded URLs after patch:" >&2
  echo "${remaining}" >&2
  exit 3
fi

echo "[patch] BeamMP-Launcher source patched OK (${#files[@]} files)"
