#!/usr/bin/env bash
# Decentralized-BMP V2 — patch BeamMP-Server source for deploy-time
# backend re-targeting.
#
# The patched binary contains a 256-byte buffer in .rodata, fronted by a
# 24-byte sentinel ("__DBMP_HOST_SENTINEL_v1\0") followed by a 4-byte
# little-endian length and 228 bytes of host-slot padding. At runtime:
#
#   * BMP_BACKEND_HOST env var, if set and non-empty, wins.
#   * Otherwise, if length > 0, the host is read from the slot.
#   * Otherwise, the binary falls back to the upstream backend.beammp.com
#     so a binary downloaded directly from this repo's GitHub release
#     behaves vanilla.
#
# A deploying Decentralized-BMP backend rewrites the length + host bytes
# *in place* on disk before serving the binary, so operators downloading
# from <that backend>/builds/... get a turnkey executable pre-pointed at
# <that backend>'s domain. See backend/scripts/fetch_builds.sh.

set -euo pipefail

if [[ ! -d "src" || ! -d "include" ]]; then
  echo "::error::Run this script from the BeamMP-Server source root" >&2
  exit 1
fi

helper_path="include/_DBMP_BackendUrl.h"

python3 - "${helper_path}" <<'PY'
import pathlib, sys

sentinel = b'__DBMP_HOST_SENTINEL_v1\x00'  # exactly 24 bytes
assert len(sentinel) == 24
length = b'\x00\x00\x00\x00'                # uint32 LE = 0 (unpatched marker)
padding = b'\xff' * 228                     # filler forces .rodata storage
blob = sentinel + length + padding
assert len(blob) == 256

init = ', '.join(f'0x{b:02X}' for b in blob)
header = f'''// Auto-generated by Decentralized-BMP V2 (patches/apply-server-patch.sh).
// See that script's header comment for the binary layout / patching scheme.
#pragma once

#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <string>

namespace dbmp {{

// 256-byte deploy-time-patchable host blob.
//
//   [0..23]  sentinel "__DBMP_HOST_SENTINEL_v1\\0"
//   [24..27] uint32 LE host length (0 = unpatched -> vanilla fallback)
//   [28..255] host string slot, NUL-padded after the active host bytes
//
// CRITICAL: the blob must be (a) emitted into the binary in full, and
// (b) read at runtime through accesses the optimiser cannot fold to
// compile-time constants. Without that, GCC/LTO sees a `const` array
// whose length-field is 0, constant-propagates through `_resolve_host()`,
// concludes the slot path is dead, and drops the array from .rodata
// entirely — leaving the deploy-time host-stamper with nothing to find
// and the binary permanently locked to the upstream fallback host.
//
// Defences:
//   * `volatile` storage  -> reads cannot be CSE'd away.
//   * `__attribute__((used, retain))` (GCC/Clang) -> linker keeps the
//     symbol even when LTO thinks it's dead. MSVC does this implicitly
//     for non-COMDAT externals.
//   * Read length through a volatile pointer so the optimiser must
//     re-fetch from memory rather than constant-fold the initialiser.
#if defined(__GNUC__) || defined(__clang__)
#  define DBMP_KEEP __attribute__((used, retain))
#else
#  define DBMP_KEEP
#endif

inline DBMP_KEEP volatile unsigned char dbmp_host_blob[256] = {{ {init} }};

inline std::string _resolve_host() {{
    if (const char* env = std::getenv("BMP_BACKEND_HOST")) {{
        if (env[0] != '\\0') return std::string(env);
    }}
    // Read length through a volatile pointer so the optimiser cannot
    // fold to the initialised-to-zero constant.
    volatile const unsigned char* p = dbmp_host_blob + 24;
    std::uint32_t len = static_cast<std::uint32_t>(p[0])
                      | (static_cast<std::uint32_t>(p[1]) << 8)
                      | (static_cast<std::uint32_t>(p[2]) << 16)
                      | (static_cast<std::uint32_t>(p[3]) << 24);
    if (len > 0 && len <= 228) {{
        // Copy out byte-by-byte so the volatile array participates in
        // the runtime read and the resulting string has no embedded NULs.
        std::string out;
        out.reserve(len);
        for (std::uint32_t i = 0; i < len; ++i) {{
            out.push_back(static_cast<char>(dbmp_host_blob[28 + i]));
        }}
        return out;
    }}
    return "backend.beammp.com";
}}

inline std::string backend_url() {{ return std::string("https://") + _resolve_host(); }}
inline std::string auth_url()    {{ return std::string("https://") + _resolve_host(); }}

}} // namespace dbmp
'''
pathlib.Path(sys.argv[1]).write_text(header, encoding="utf-8")
PY

echo "[patch] wrote ${helper_path}"

# Sweep src/+include/ for the two upstream URL literals and replace them
# with the helper calls. Inject our header include into any TU that needed
# rewriting.
patch_count=0
for literal_pair in \
    'https://backend.beammp.com|dbmp::backend_url()' \
    'https://auth.beammp.com|dbmp::auth_url()'; do
  literal="${literal_pair%%|*}"
  call="${literal_pair##*|}"
  # shellcheck disable=SC2207
  files=($(grep -rl --include='*.cpp' --include='*.h' --include='*.hpp' \
      "\"${literal}\"" src include 2>/dev/null || true))
  for f in "${files[@]}"; do
    if ! grep -q '_DBMP_BackendUrl\.h' "${f}"; then
      python3 - "${f}" <<'PY'
import pathlib, sys
p = pathlib.Path(sys.argv[1])
lines = p.read_text(encoding="utf-8").splitlines(keepends=True)
inserted = False
for i, line in enumerate(lines):
    if line.lstrip().startswith("#include"):
        lines.insert(i, '#include "_DBMP_BackendUrl.h"\n')
        inserted = True
        break
if not inserted:
    lines.insert(0, '#include "_DBMP_BackendUrl.h"\n')
p.write_text("".join(lines), encoding="utf-8")
PY
    fi
    python3 - "${f}" "${literal}" "${call}" <<'PY'
import pathlib, sys
p = pathlib.Path(sys.argv[1])
text = p.read_text(encoding="utf-8")
new = text.replace(f'"{sys.argv[2]}"', sys.argv[3])
if new != text:
    p.write_text(new, encoding="utf-8")
PY
    echo "[patch] rewrote ${f} (${literal})"
    patch_count=$((patch_count + 1))
  done
done

if [[ ${patch_count} -eq 0 ]]; then
  echo "::error::no occurrences of upstream URL literals found — upstream changed shape?" >&2
  exit 2
fi

remaining=$(grep -rE --include='*.cpp' --include='*.h' --include='*.hpp' \
    '"https://(backend|auth)\.beammp\.com"' src include 2>/dev/null || true)
if [[ -n "${remaining}" ]]; then
  echo "::error::leftover hard-coded URLs after patch:" >&2
  echo "${remaining}" >&2
  exit 3
fi

echo "[patch] BeamMP-Server source patched OK (${patch_count} substitutions)"
